name: Run Unit Tests
on: [workflow_dispatch, pull_request]
jobs:
  Unit-Tests:
    strategy:
      matrix:
        os:
          - macos-14
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone pyenv
        run: git clone https://github.com/pyenv/pyenv.git ~/.pyenv

      - name: Run the CI build script
        run: |
          PATH=$HOME/.pyenv/shims:$PATH:$HOME/.pyenv/bin
          # export SETUPTOOLS_USE_DISTUTILS=stdlib
          pyenv install --skip-existing 3.8.12
